#!/bin/bash

upSeconds=$(cut -d. -f1 /proc/uptime)
secs=$((upSeconds%60))
mins=$((upSeconds/60%60))
hours=$((upSeconds/3600%24))
days=$((upSeconds/86400))
UPTIME=$(printf "%d dias, %02dh%02dm%02ds" "$days" "$hours" "$mins" "$secs")

read one five fifteen rest < /proc/loadavg

HOSTNAME=$(hostname)
OS=$(grep PRETTY_NAME /etc/os-release | cut -d= -f2 | tr -d '"')
KERNEL=$(uname -r)
CPU=$(grep "model name" /proc/cpuinfo | head -1 | cut -d: -f2 | sed 's/^ //')
VCPU=$(nproc)
MEMFREE=$(grep MemAvailable /proc/meminfo | awk '{print $2}')
MEMTOTAL=$(grep MemTotal /proc/meminfo | awk '{print $2}')
DISK=$(df -h / | awk 'NR==2 {print $3 " usados / " $4 " livres (" $5 ")"}')
IPV4=$(ip -4 addr show scope global | awk '/inet / {print $2}' | head -1)
IPV6=$(ip -6 addr show scope global | awk '/inet6 / {print $2}' | head -1)
MAC=$(ip link | awk '/link\/ether/ {print $2}' | head -1)
PROCS=$(ps ax --no-headers | wc -l)

SEP_COL=50
TOTAL_COL=120

line_full() {
    printf '%*s\n' "$TOTAL_COL" '' | tr ' ' '-'
}

print_line() {
    printf "%s" "$1"
    printf "\033[%sG| %s\n" "$SEP_COL" "$2"
}

echo
line_full

print_line '        ███╗   ███╗██╗   ██╗██████╗ ' "Data/Hora..........: $(date '+%d/%m/%Y %H:%M:%S')"
print_line '        ████╗ ████║██║   ██║╚════██╗' "Hostname...........: ${HOSTNAME}"
print_line '        ██╔████╔██║██║   ██║ █████╔╝' ""
print_line '        ██║╚██╔╝██║╚██╗ ██╔╝██╔═══╝ ' "Sistema............: ${OS}"
print_line '        ██║ ╚═╝ ██║ ╚████╔╝ ███████╗' "Kernel.............: ${KERNEL}"
print_line '        ╚═╝     ╚═╝  ╚═══╝  ╚══════╝' ""

print_line '' "Uptime.............: ${UPTIME}"
print_line '         CONSULTORIA E SUPORTE EM TI' "CPU................: ${CPU}"
print_line '' "vCPU...............: ${VCPU}"
print_line '----------------------------------------' "Load...............: ${one}, ${five}, ${fifteen}"
print_line '' ""

print_line 'MV2 Solucoes' "Memoria............: ${MEMFREE}kB Livre / ${MEMTOTAL}kB Total"
print_line 'Consultoria e Suporte em TI' "Disco..............: ${DISK}"
print_line 'https://mv2solutions.com.br' ""
print_line 'WhatsApp: (24) 99912-6059' "IPv4...............: ${IPV4}"
print_line '' "IPv6...............: ${IPV6}"
print_line '' "MAC................: ${MAC}"
print_line '' ""
print_line '' "Processos..........: ${PROCS}"

line_full
echo
